"""empty message

Revision ID: 800b198ad768
Revises: 5e9dfceac308
Create Date: 2022-10-23 19:51:22.607744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800b198ad768'
down_revision = '5e9dfceac308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('api_key', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'api_key')
    # ### end Alembic commands ###
