"""empty message

Revision ID: c4dab5b300dc
Revises: e46ddfb5bb42
Create Date: 2022-08-24 18:52:24.193571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4dab5b300dc'
down_revision = 'e46ddfb5bb42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curso', sa.Column('formacao_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'curso', 'formacao', ['formacao_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'curso', type_='foreignkey')
    op.drop_column('curso', 'formacao_id')
    # ### end Alembic commands ###
